### ISSUE TITLE
OpenSSL failures

### ISSUE THREAD

**Issue by bbuchalter** [jetsgit/spree_tax_cloud#69]
The CA in https://github.com/jetsgit/spree_tax_cloud/blob/master/config/initializers/fix_ssl.rb#L9 is no longer valid and returns the following errors: `OpenSSL::SSL::SSLError:
       SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

**Comment by jetsgit** [comment]
No bandwidth on this, closing
